# @package task_specific_constraints
N: 8
num_inputs: 6
num_outputs: 2
w_inp: [[1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
        [0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
        [0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
        [0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
        [0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
        [0.0, 0.0, 0.0, 0.0, 0.0, 1.0],
        [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
        [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]
w_out: [[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
        [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]]
inp_connectivity_mask: [[1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                        [0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
                        [0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
                        [0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
                        [0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
                        [0.0, 0.0, 0.0, 0.0, 0.0, 1.0],
                        [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                        [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]
rec_connectivity_mask: [[ 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
                        [ 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
                        [ 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
                        [ 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
                        [ 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
                        [ 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
                        [ 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
                        [ 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]]
out_connectivity_mask: [[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
                        [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]]