# @package task_specific_constraints
N: 5
num_inputs: 3
num_outputs: 1
w_inp: [[1.0, 0.0, 0.0],
        [0.0, 1.0, 0.0],
        [0.0, 0.0, 1.0],
        [0.0, 0.0, 0.0],
        [0.0, 0.0, 0.0]]
w_out: [[1.0, 1.0, 1.0, 1.0, 1.0]]
inp_connectivity_mask: [[1.0, 0.0, 0.0],
                        [0.0, 1.0, 0.0],
                        [0.0, 0.0, 1.0],
                        [0.0, 0.0, 0.0],
                        [0.0, 0.0, 0.0]]
rec_connectivity_mask: [[ 1.0, 1.0, 1.0, 1.0, 1.0],
                        [ 1.0, 1.0, 1.0, 1.0, 1.0],
                        [ 1.0, 1.0, 1.0, 1.0, 1.0],
                        [ 1.0, 1.0, 1.0, 1.0, 1.0],
                        [ 1.0, 1.0, 1.0, 1.0, 1.0]]
out_connectivity_mask: [[1.0, 1.0, 1.0, 1.0, 1.0]]