# @package _global_
defaults:
  - /LC_fitter: standard
  - _self_
configs_path: "../../configs"
n_repeats: 5
n_units: 10
RNN_subfolder: "0.00759_CDDM_relu;N=94;lmbdo=0.3;orth_inp_only=True;lmbdr=0.5;lr=0.005;maxiter=5000"
RNN_parent_folder: "CDDM_relu_constrained=True"

